spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
#    active: prod
    active: dev
swagger:
  production: false
  basic:
    enable: false
    username: jeecg
    password: jeecg1314