spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: dev #开发环境配置
#    active: prod #业务网环境配置
#    active: cfcc #公司内网环境配置
#    active: heb #哈尔滨测试环境配置
swagger:
  production: false
  basic:
    enable: false
    username: jeecg
    password: jeecg1314